// regions.js — static metadata about Brodmann areas.
//
// Per-patient data (which BAs are present, their colors, the mesh, the
// electrodes) lives in data.js (generated by scripts/export_for_viewer.py).
// This file holds patient-independent reference info: function descriptions,
// schematic group labels, and the schematic 2D layout used by brain2d.jsx.

// Short clinical description shown in the side panel "Region detail" view.
// Kept in sync with src/labeling.BRODMANN_LABELS but adds a one-line function blurb.
window.NEM_BA_INFO = {
  1:  { name: "Primary Somatosensory Cortex",       fn: "Tactile discrimination." },
  2:  { name: "Primary Somatosensory Cortex",       fn: "Somatosensory integration." },
  3:  { name: "Primary Somatosensory Cortex",       fn: "Tactile reception from skin and joints." },
  4:  { name: "Primary Motor Cortex (M1)",          fn: "Initiates voluntary muscle movement." },
  5:  { name: "Somatosensory Association Cortex",   fn: "Integrates touch and proprioception." },
  6:  { name: "Premotor & Supplementary Motor",     fn: "Planning and sequencing of movement." },
  7:  { name: "Superior Parietal Lobule",           fn: "Visuomotor coordination, spatial orientation." },
  8:  { name: "Frontal Eye Fields",                 fn: "Voluntary eye movement control." },
  9:  { name: "Dorsolateral Prefrontal Cortex",     fn: "Working memory, executive control." },
  10: { name: "Anterior Prefrontal Cortex",         fn: "Multitasking, prospective memory." },
  11: { name: "Orbitofrontal Cortex",               fn: "Reward processing, decision making." },
  17: { name: "Primary Visual Cortex (V1)",         fn: "Initial cortical processing of vision." },
  18: { name: "Secondary Visual Cortex (V2)",       fn: "Visual feature integration." },
  19: { name: "Associative Visual Cortex",          fn: "Higher-order visual processing." },
  20: { name: "Inferior Temporal Gyrus",            fn: "Object and face recognition." },
  21: { name: "Middle Temporal Gyrus",              fn: "Language and semantic memory." },
  22: { name: "Superior Temporal / Wernicke's",     fn: "Auditory and language comprehension." },
  37: { name: "Fusiform / Inferior Temporal",       fn: "Face, word, and color recognition." },
  39: { name: "Angular Gyrus",                      fn: "Reading, math, attention to space." },
  40: { name: "Supramarginal Gyrus",                fn: "Phonological processing, spatial perception." },
  41: { name: "Primary Auditory Cortex",            fn: "Initial cortical processing of sound." },
  42: { name: "Secondary Auditory Cortex",          fn: "Sound recognition and integration." },
  44: { name: "Pars Opercularis (Broca's)",         fn: "Speech production." },
  45: { name: "Pars Triangularis (Broca's)",        fn: "Semantic aspects of language." },
  46: { name: "Dorsolateral Prefrontal Cortex",     fn: "Cognitive control, working memory." },
  47: { name: "Inferior Prefrontal Cortex",         fn: "Language processing, response inhibition." },
};

// Default fallback used when a BA we don't have metadata for shows up.
window.NEM_BA_FALLBACK = { name: "Unknown region", fn: "No clinical annotation available." };

// Helper: read a BA from window.NEM_DATA.regions if present, else NEM_BA_INFO,
// else a generic fallback. Returns a uniform { ba, name, fn, group, color }.
window.nemRegionInfo = function (ba) {
  const fromData = window.NEM_DATA && window.NEM_DATA.regions
    ? window.NEM_DATA.regions[String(ba)]
    : null;
  const fromStatic = window.NEM_BA_INFO[ba] || window.NEM_BA_FALLBACK;
  return {
    ba: ba,
    name: (fromData && fromData.name) || fromStatic.name,
    fn:   fromStatic.fn,
    group: (fromData && fromData.group) || "Other",
    color: (fromData && fromData.color) || "#888888",
    schematic_id: (fromData && fromData.schematic_id) || "unknown",
  };
};
